server:
  port: 8080

spring:
  application:
    name: social-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:aws}
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:glamme}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: 0

aws:
  region: ${AWS_REGION:us-east-1}
  s3:
    bucket: ${S3_BUCKET:glamme-media}
  opensearch:
    endpoint: ${OPENSEARCH_ENDPOINT:}
    collection: ${OPENSEARCH_COLLECTION:social}
  eventbridge:
    bus-name: ${EVENTBRIDGE_BUS_NAME:glamme-bus}
  secrets:
    database-arn: ${DATABASE_SECRET_ARN:}
    opensearch-arn: ${OPENSEARCH_SECRET_ARN:}

social:
  media:
    max-file-size: 10MB
    allowed-types: "image/jpeg,image/png,image/gif,video/mp4"
  posts:
    max-content-length: 280
    cache-ttl-hours: 24
  hashtags:
    trending-limit: 10
    trending-window-hours: 24

logging:
  level:
    tech.ceesar.glamme: INFO
    software.amazon.awssdk: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized