#!/bin/bash

# GitHub Repository Configuration Script for GlamMe CI/CD
# This script provides all the necessary commands and values for configuring GitHub repository secrets

set -e

# Configuration
REPO_NAME="ceesartech/Glam-Me"
AWS_REGION="us-east-1"
ACCOUNT_ID="476114151082"
ROLE_ARN="arn:aws:iam::476114151082:role/GlamMe-CICD-Role"

echo "🚀 GitHub Repository Configuration for GlamMe CI/CD"
echo "=================================================="
echo ""
echo "📋 Repository: https://github.com/$REPO_NAME"
echo ""
echo "🔑 REQUIRED GitHub Repository Secrets:"
echo "======================================"
echo ""
echo "Secret Name: AWS_ROLE_ARN"
echo "Secret Value: $ROLE_ARN"
echo ""
echo "Secret Name: AWS_REGION"
echo "Secret Value: $AWS_REGION"
echo ""
echo "Secret Name: ACCOUNT_ID"
echo "Secret Value: $ACCOUNT_ID"
echo ""
echo "🌐 GitHub Secrets Configuration:"
echo "==============================="
echo ""
echo "1. MANUAL CONFIGURATION:"
echo "   - Open: https://github.com/$REPO_NAME/settings/secrets/actions"
echo "   - Click: 'New repository secret'"
echo "   - Add each secret above with exact names and values"
echo ""
echo "2. USING GITHUB CLI (if installed):"
echo "   gh secret set AWS_ROLE_ARN --body '$ROLE_ARN' --repo $REPO_NAME"
echo "   gh secret set AWS_REGION --body '$AWS_REGION' --repo $REPO_NAME"
echo "   gh secret set ACCOUNT_ID --body '$ACCOUNT_ID' --repo $REPO_NAME"
echo ""
echo "3. VERIFY SECRETS:"
echo "   gh secret list --repo $REPO_NAME"
echo ""
echo "📊 MONITOR PIPELINE:"
echo "=================="
echo ""
echo "After configuring secrets:"
echo "1. Go to: https://github.com/$REPO_NAME/actions"
echo "2. Check if pipeline is running (should start automatically)"
echo "3. If not running, manually trigger:"
echo "   - Click 'GlamMe CI/CD Pipeline'"
echo "   - Click 'Run workflow'"
echo "   - Select environment: 'dev'"
echo "   - Click 'Run workflow'"
echo ""
echo "⏱️ EXPECTED PIPELINE DURATION:"
echo "============================"
echo ""
echo "• Test & Build: 15-20 minutes"
echo "• Build & Push: 10-15 minutes"
echo "• Deploy Infrastructure: 5-10 minutes"
echo "• Deploy Services: 5-10 minutes"
echo "• Test Deployment: 2-5 minutes"
echo "• Total: ~45-60 minutes"
echo ""
echo "✅ SUCCESS CRITERIA:"
echo "==================="
echo ""
echo "• All jobs complete with green checkmarks"
echo "• No failed steps in any job"
echo "• ECR repositories contain new images"
echo "• ECS cluster shows running services"
echo "• CloudFormation stack shows CREATE_COMPLETE"
echo ""
echo "🔍 TROUBLESHOOTING:"
echo "=================="
echo ""
echo "If pipeline fails:"
echo "1. Check GitHub Actions logs for detailed errors"
echo "2. Verify AWS credentials and permissions"
echo "3. Check CDK synthesis and deployment issues"
echo "4. Review ECS service deployment logs"
echo ""
echo "📞 SUPPORT:"
echo "=========="
echo ""
echo "• GitHub Actions: https://github.com/$REPO_NAME/actions"
echo "• AWS Console: https://console.aws.amazon.com/"
echo "• CloudWatch Logs: Check /ecs/glamme-cluster/*"
echo ""
echo "🎉 READY FOR AUTOMATED DEPLOYMENT!"
echo "=================================="
echo ""
echo "Once secrets are configured, your GlamMe platform will have:"
echo "✅ Automated testing and building"
echo "✅ Docker image creation and ECR push"
echo "✅ Infrastructure deployment with CDK"
echo "✅ ECS service orchestration"
echo "✅ Health checks and monitoring"
echo "✅ Multi-environment support"
echo ""
echo "🚀 Your CI/CD pipeline is ready to deploy GlamMe automatically!"
