server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bookingdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update

stripe:
  apiKey: ${STRIPE_API_KEY}
  webhookSecret: ${STRIPE_WEBHOOK_SECRET}
  successUrl: ${FRONTEND_URL:http://localhost:3000}/booking-success?session_id={CHECKOUT_SESSION_ID}
  cancelUrl: ${FRONTEND_URL:http://localhost:3000}/booking-cancel

google:
  credentials:
    file: ${GOOGLE_CREDENTIALS_FILE:credentials.json}
  calendar:
    id: ${GOOGLE_CALENDAR_ID:primary}