server:
  port: 8080

spring:
  main:
    banner-mode: "off"

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:YOUR_GOOGLE_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET:YOUR_GOOGLE_SECRET}
            scope: openid,profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID:}
            client-secret: ${FACEBOOK_CLIENT_SECRET:}
            scope: public_profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          amazon:
            client-id: ${AMAZON_CLIENT_ID:}
            client-secret: ${AMAZON_CLIENT_SECRET:}
            scope: profile
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
    user:
      name-attribute: email   # map user’s principal to email

  thymeleaf:
    enabled: false

vaadin:
  servlet:
    productionMode: true