package tech.ceesar.glamme.matching.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

@Entity
@Table(name = "matches")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Match {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    @Column(name = "customer_id", nullable = false)
    private String customerId;
    
    @Column(name = "stylist_id", nullable = false)
    private String stylistId;
    
    @Column(name = "match_score")
    private Double matchScore;
    
    @Column(name = "match_type")
    @Enumerated(EnumType.STRING)
    private MatchType matchType;
    
    @Column(name = "status")
    @Enumerated(EnumType.STRING)
    private Status status;
    
    @Column(name = "requested_service")
    @Enumerated(EnumType.STRING)
    private Stylist.Service requestedService;
    
    @Column(name = "preferred_date")
    private LocalDateTime preferredDate;
    
    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;

    @Column(name = "match_reason", columnDefinition = "TEXT")
    private String matchReason;

    @Column(name = "algorithm")
    @Enumerated(EnumType.STRING)
    private Algorithm algorithm;
    
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;
    
    @Column(name = "expires_at")
    private LocalDateTime expiresAt;
    
    @Column(name = "responded_at")
    private LocalDateTime respondedAt;
    
    public enum MatchType {
        ALGORITHMIC, // Generated by matching algorithm
        MANUAL, // Manually created by customer
        RECOMMENDED, // Recommended by system
        IMAGE_BASED, // Created from image service integration
        DIRECT, // Direct booking (bypass matching)
        HAIRSTYLE_QUERY // Based on hairstyle search query
    }
    
    public enum Status {
        PENDING, // Waiting for stylist response
        ACCEPTED, // Stylist accepted the match
        DECLINED, // Stylist declined the match
        EXPIRED, // Match expired
        CANCELLED, // Customer cancelled the match
        POTENTIAL // Potential match (not yet confirmed/saved)
    }

    public enum Algorithm {
        ELO_RATING, // Elo rating based algorithm
        COSINE_SIMILARITY, // Cosine similarity algorithm
        COLLABORATIVE_FILTERING, // Collaborative filtering
        GALE_SHAPLEY, // Gale-Shapley stable matching algorithm
        HYBRID // Combination of multiple algorithms
    }
}