server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:shoppingdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update

aws:
  region: ${AWS_REGION:us-east-1}
  s3:
    bucket: ${AWS_S3_BUCKET:shopping-media}

stripe:
  apiKey: ${STRIPE_API_KEY}
  webhookSecret: ${STRIPE_WEBHOOK_SECRET}
  successUrl: ${FRONTEND_URL:http://localhost:3000}/order-success?session_id={CHECKOUT_SESSION_ID}
  cancelUrl: ${FRONTEND_URL:http://localhost:3000}/order-cancel

easypost:
  apiKey: ${EASYPOST_API_KEY}